export { default as Welcome } from './welcome';
export { default as SignIn } from './signIn';
export { default as SignUp } from './signUp';
export { default as MyCard } from './myCard';
export { default as MyCollection } from './myCollection';
export { default as Main } from './main';
export { default as MyCoupons } from './myCoupons';
export { default as AdditionalDetails } from './additionalDetails';
export { default as Notifications } from './notifications';
